### PR TITLE
Add hooks

### PR DESCRIPTION
**Pull request by yields**

### CODE REVIEW

**Comment by yields** [comment]
##### Adds a minimal `.hook()` system

It's got a single hook called `ignore` for now, it allows you to ignore specific `msg`s (facade) for each integration.

##### Preserve options.

Since we need configurations for hooks i tweaked `._options()` to preserve options in `.options` property, so that hooks and such would be able to access configuration easily.

cc @ianstormtaylor

**Comment by gjohnson** [comment]
Maybe instead of `.hook("ignore")`, just `.filter(fn)`? Archive could just be a filter. Just syntax details though, looks great though!

```js
analytics.filter(function(msg){
  
})
```

**Comment by yields** [comment]
Ah that was my initial idea, but i thought that `.hook()` is more extensible, in the future we can add stuff like:

```js
.hook('transform', function(integration, msg){
  var name = integration.name;
  var transforms = this.options.transforms;
  if (!transforms[name]) return msg;
  return transform(transforms, msg); // returns a new msg :D
});
```

**Comment by yields** [comment]
only problem i can see with `.hook()` is that it might get tricky with multiple hooks :/

**Comment by gjohnson** [comment]
@yields :bow:

**Pull request closed without merging**
